cleanup
Beramos/DS-Julia2925 pull request #148
Opened 2024-01-27 19:32 UTC by DaanVanHauwermeiren

A simple cleanup of all the files:
remove some old code, check if the notebooks still run on new julia and pluto version

- update gitignore
- remove legacy code
- update project and manifest: only need pluto as the other libs are loaded automatically in the notebook
- update gitignore: we need the notebooks folder
- update notebooks to new julia version and new libs, all seem ok except for issues 145 146 147

2024-01-28 07:12 UTC, Beramos requested changes
Some rogue files but other than that thanks for the effort!

2024-01-28 07:12 UTC, Beramos commented on legacy/examples/error_propagation.jl
> -Created on 03/02/2021 09:20:46
Might be nice to keep this one in?

2024-01-28 07:12 UTC, Beramos commented on notebooks/day1/03-exercises backup 1 backup 1.jl
I think we need another backup of this file :rofl: 

On a serious note pls remove.

2024-01-28 07:12 UTC, Beramos commented on notebooks/day1/03-exercises backup 1.jl
On a serious note pls remove.

2024-01-28 07:12 UTC, Beramos commented on notebooks/day1/aprettybird.jpg
I remember this img being downloaded from url so no file should be here. I checked and could not find a reference to this file. Please double check though.

2024-01-28 07:12 UTC, Beramos commented on notebooks/day1/aprettybird.jpg
https://github.com/search?q=repo%3ABeramos%2FDS-Julia2925%20aprettybird&type=code

2024-01-28 07:12 UTC, Beramos commented on notebooks/examples/performance_convolution backup 1.jl
please remove

2024-01-28 07:12 UTC, Beramos commented on notebooks/examples/performance_sum backup 1.jl
please remove

2024-01-28 07:13 UTC, Beramos commented on legacy/examples/error_propagation.jl
> -Created on 03/02/2021 09:20:46
With in, I mean move to examples.

2024-01-28 07:13 UTC, Beramos commented
I would in general retain a little more examples.

2024-01-28 16:07 UTC, DaanVanHauwermeiren commented on notebooks/day1/03-exercises backup 1 backup 1.jl
oh no, I most likely did a `git add *` :cry:

2024-01-28 16:26 UTC, DaanVanHauwermeiren commented
> I would in general retain a little more examples.

going to rewind and move `legacy/examples` to `examples` + add a readme

2024-02-01 16:20 UTC, Beramos approved these changes
I'm merging this. I will move the typo to separate issue

2024-02-01 16:20 UTC, Beramos commented on notebooks/day1/01-basics.jl
> +In mathematics, he has kins called narcissistic numbers - numbers that can't get enough of themselves. In particular, they are numbers that are the sum of their digits when raised to the power of the
typo @MichielStock

2024-02-01 16:20 UTC, Beramos commented on notebooks/day1/01-basics.jl
> +In mathematics, he has kins called narcissistic numbers - numbers that can't get enough of themselves. In particular, they are numbers that are the sum of their digits when raised to the power of the
he has kins...  not sure what that means or just typo

2024-02-01 16:20 UTC, merged